### PR TITLE
Support raw results in find in batches

### PR DESCRIPTION
**Pull request by zewelor**
Hi

I've added support to return pure results instead of records in find in batches method. I've added it support indexes without AR models, or any models at all. When I just need pure results, but using find in batches because of data size.

### CODE REVIEW

**Comment by mrkamel** [comment]
Thanks for this PR. Much appreciated.

Just a few tiny issues:

- i'm not quite sure regarding the `:raw_results` option (naming and complexity wise). i'd definitely favor a separate method `find_results_in_batches`

- `no_more_results = use_raw_hashes ? criteria.last_page? : criteria.records.empty?` doesn't make sense to me. there shouldn't be any difference in how to detect whether or not the end is reached between using the raw results or not. However, as i'm reading through the code again, `criteria.records.empty?` has a probability that the records have been deleted while scrolling through the ES result such that there is a risk of terminating too early. Contrary, `criteria.last_page?` isn't correct because we aren't paging (there is no current page/offset), but we are scrolling. We should simply head over to `criteria.results.empty?`

- your PR is missing tests

**Comment by mrkamel** [comment]
Correction: we should use `criteria.ids.empty?` to avoid the overhead of `Hashie::Mash`'erizing the results in case we want the db records to be yielded.

**Comment by zewelor** [comment]
@mrkamel 
Originally I've added 2 methods, find_each_results and find_results_in_batches, but they were just duplicates except of returning hash vs model. Maybe other approch would be to add some method in Index class that will specify default return data type like Hash vs initialized model instance ?

**Comment by mrkamel** [comment]
Do you think you can package up another PR - or do you need more help?

**Comment by zewelor** [comment]
Sure I will make another PR. Just need some time to get back to it. I will probably also make other PR. All around  some optimizations in bulk request. From what I saw, http client doesn't do compression or persistent connection. I got plan to make PR with this also, need to read more code to see how to add it nicely.

**Comment by mrkamel** [comment]
hi, i've added a `#find_results_in_batches` method, as this was a minor effort and i'm going to release a new version. Hope this is ok for you.

**Comment by zewelor** [comment]
@mrkamel Thanks !

**Pull request closed without merging**
